# sample config file for offline BCQ with buffer size of 1000, rand prob of 10%, second-best prob of 25%, random seed 1
2nd_action_p: 0.25
annealing: true
annealing_start: 5000
annealing_steps: 1000
bcq_threshold: 0.3
buffer_name: bcq_fc0
ddqn: false
device: cpu
episode_max_len: 10
episodes_per_epoch: 50
episodes_per_test: 10
epsilon: 1
final_epsilon: 0.1
folder_location: models\
folder_name: buf1000_rand0.1_second0.25_seed6
gamma: 0.95
hyperparams: buf1000_rand0.1_second0.25
is_learning: true
is_testing: true
learning_frequency: 1
learning_rate: 0.001
minibatch_size: 32
model_type: buf1000_rand0.1_second0.25_BCQ
network_size: bcq_fc
normalize: 5
num_epochs: 201
num_experiments: 1
online_ql: false
option_env: true
printing_period: 10
rand_action_p: 0.1
random_seed: 1
rendering: false
replay_max_size: 1000
replay_min_size: 1000
saving_period: 200
sq_learning: true
test: false
test_data_folder: buffers\test_states
test_epsilon: 0.0
unique_run_id: wceg8n0y
update_freq: 1000
val_buffer_size: 250
writing_period: 1
