2nd_action_p: 0
annealing: true
annealing_start: 5000
annealing_steps: 10000
bcq_threshold: 0.3
buffer_name: bcq_fc0
ddqn: true
device: cpu
episode_max_len: 50
episodes_per_epoch: 20
episodes_per_test: 10
epsilon: 1
final_epsilon: 0.1
folder_location: \models\
folder_name: online
gamma: 0.9
is_learning: true
is_testing: true
learning_frequency: 1
learning_rate: 0.0005
minibatch_size: 32
network_size: dqn_fc
normalize: 5
num_epochs: 501
num_experiments: 1
online_ql: true
option_env: true
printing_period: 10
rand_action_p: 0.25
random_seed: 3
rendering: false
replay_max_size: 50000
replay_min_size: 1000
saving_period: 100
sq_learning: true
test: false
test_data_folder: buffers\test_states
test_epsilon: 0.0
update_freq: 1000
val_buffer_size: 250
writing_period: 1
wandb_key: None
